server:
  port: 10010
spring:
  application:
    name: mall-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    mall-provider-pms: /pms/**
    mall-provider-sms: /sms/**